const mockedState = {
  services: [
    {
      _id: '6135cec0464783204dfe5612',
      description: 'Servicio de Maquillaje Social para fiestas y eventos intenso o natural teniendo en cuenta el tipo de evento, el vestido, el peinado y tu estilo para crear un look perfecto.',
      duration: '120',
      name: 'Maquillaje',
      picture: 'https://i.ibb.co/r53cmdd/1626077210.jpg',
      price: 80,
      type: 'make_up_and_hairstyles',
    },
    {
      _id: '6135cec0464783204dfe5612',
      description: 'Servicio de Maquillaje Social para fiestas y eventos intenso o natural teniendo en cuenta el tipo de evento, el vestido, el peinado y tu estilo para crear un look perfecto.',
      duration: '120',
      name: 'Peinado',
      picture: 'https://i.ibb.co/r53cmdd/1626077210.jpg',
      price: 60,
      type: 'make_up_and_hairstyles',
    },
  ],
  categoryServices: [
    {
      _id: '6135cec0464783204dfe5612',
      description: 'Servicio de Maquillaje Social para fiestas y eventos intenso o natural teniendo en cuenta el tipo de evento, el vestido, el peinado y tu estilo para crear un look perfecto.',
      duration: '120',
      name: 'Maquillaje',
      picture: 'https://i.ibb.co/r53cmdd/1626077210.jpg',
      price: 80,
      type: 'make_up_and_hairstyles',
    },
    {
      _id: '6135cec0464783204dfe5612',
      description: 'Servicio de Maquillaje Social para fiestas y eventos intenso o natural teniendo en cuenta el tipo de evento, el vestido, el peinado y tu estilo para crear un look perfecto.',
      duration: '120',
      name: 'Peinado',
      picture: 'https://i.ibb.co/r53cmdd/1626077210.jpg',
      price: 60,
      type: 'make_up_and_hairstyles',
    },
  ],
  currentCategory: 'make_up_and_hairstyles',
  currentService: {
    _id: '6135cec0464783204dfe5612',
    description: 'Servicio de Maquillaje Social para fiestas y eventos intenso o natural teniendo en cuenta el tipo de evento, el vestido, el peinado y tu estilo para crear un look perfecto.',
    duration: '120',
    name: 'Peinado',
    picture: 'https://i.ibb.co/r53cmdd/1626077210.jpg',
    price: 80,
    type: 'make_up_and_hairstyles',
  },
  currentUser: {
    _id: '612cecf6a7b929f51af44790',
    bookings: ['FirstBooking'],
    cart: '612cec70a7b929f51af4478a',
    email: 'mireia@leon.com',
    gender: 'Female',
    name: 'Mireia',
    password: '12345',
    picture: 'https://i.pinimg.com/originals/e7/cd/21/e7cd217265a2a8f03484820eb893c070.jpg',
    surname: 'Leon',
  },
  cart: {
    _id: '123',
    services: [
      {
        _id: '612cec70a7b929f51af4478a',
        amount: 2,
        service: {
          _id: '613a5ca16919dcbd1bbbbc4d',
          description: 'Servicio de Maquillaje',
          duration: '120',
          name: 'Peinado',
          picture: 'https://i.ibb.co/r53cmdd/1626077210.jpg',
          price: 80,
          type: 'make_up_and_hairstyles',
        },
      },
    ],
  },
  keyword: 'Peinado',
  selectedCategory: 'make_up_and_hairstyles',
  selectedSortPrice: 'ABC',
};

export default mockedState;
